/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-09 09:38:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	\r\n");
      out.write("	<title>Registration Page</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/register.css\">\r\n");
      out.write("	<!--Bootstrap website link to get social media icons(use.fontawesome.com)-->\r\n");
      out.write("	<link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      href=\"https://use.fontawesome.com/releases/v5.13.0/css/all.css\"\r\n");
      out.write("      integrity=\"sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V\"\r\n");
      out.write("      crossorigin=\"anonymous\"/>\r\n");
      out.write("	  <script src=\"JS/register.js\"></script>\r\n");
      out.write("	<script src=\"\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--Header-->\r\n");
      out.write("	<!--Navigation Bar-->\r\n");
      out.write("	\r\n");
      out.write("	<nav>\r\n");
      out.write("		<a href=\"home.html\"><img src=\"Images/logo.jpeg\" class=\"logo\"></a>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"home.html\">Home</a></li>\r\n");
      out.write("			<li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("			<li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("			<li><a href=\"results.html\">Results</a></li>\r\n");
      out.write("			<li><a href=\"Exams.html\">Exams</a></li>\r\n");
      out.write("			<div class=\"dropdown\">\r\n");
      out.write("				<button class=\"dropbtn\">Profile\r\n");
      out.write("				<i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("				<div class=\"dropdown-content\">\r\n");
      out.write("                    <a href=\"login.html\">Sign In</a>\r\n");
      out.write("				</div>		\r\n");
      out.write("			</div>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("<div class = register_page>\r\n");
      out.write("	<!--Register Form-->\r\n");
      out.write("	<div class = form>\r\n");
      out.write("   \r\n");
      out.write("        <body>\r\n");
      out.write("            <div class=\"register-wrapper\">\r\n");
      out.write("                <div class=\"form\">\r\n");
      out.write("                    <form action=\"##\" method=\"POST\" id=\"reg_form\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label ><b>Quiz:</b></label>\r\n");
      out.write("                                <input class=\"form-element\" type=\"text\" id=\"fname\" name=\"quiz\" placeholder=\"Enter Quiz..\" autocomplete=\"off\" required>\r\n");
      out.write("                                <small style=\"color:red;\"></small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"lname\"><b>Anser1 :</b></label>\r\n");
      out.write("                                <input class=\"form-element\" type=\"text\" id=\"lname\" name=\"Anser1\" placeholder=\"Enter Anser1..\" autocomplete=\"off\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\"><b>Anser2 :</b></label>\r\n");
      out.write("                                <input class=\"form-element\" type=\"text\" id=\"email\" name=\"Anser2\" placeholder=\"Enter Anser2..\" autocomplete=\"off\">\r\n");
      out.write("                                <small style=\"color:red;\"></small>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"birthday\"><b>Anser3 :</b></label>\r\n");
      out.write("                                <input class=\"form-element\" type=\"text\" id=\"birthday\"  placeholder=\"Enter Anser3..\" name=\"Anser3\" required>\r\n");
      out.write("        \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"password\"><b>Anser4 :</b> </label>\r\n");
      out.write("                                <input class=\"form-element\" type=\"text\" id=\"text\" name=\"Anser4\" placeholder=\"Enter Anser4..\" autocomplete=\"off\">\r\n");
      out.write("                                <small style=\"color:red;\"></small>\r\n");
      out.write("                            </div>\r\n");
      out.write("     \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"w-100 p-1\">\r\n");
      out.write("                            <input type=\"submit\" class=\"submit_btn float-right\" id=\"submit_btn\" value=\"Submit\">\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                    </form>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
