/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-05 15:08:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class exams_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <!-- CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/exam.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- JS -->\r\n");
      out.write("    <script src=\"JS/exam.js\"></script>\r\n");
      out.write("    <title>Exam Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"quiz-page\">\r\n");
      out.write("        <div id=\"headder\">\r\n");
      out.write("            <a href=\"home.html\"><span class=\"page-name\">Online Exams</span>\r\n");
      out.write("            <span class=\"page-slogan\">Making exams easy</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"quiz-body\">\r\n");
      out.write("            <div id=\"headder\">\r\n");
      out.write("                <span name=\"course-name\">Test: not selected</span>\r\n");
      out.write("                <div class=\"btn-container\">\r\n");
      out.write("                    <button class=\"button\" onclick=\"startQuiz(this)\" id=\"start-quiz\">Start Quiz</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"quiz-container\">\r\n");
      out.write("                <div id=\"tests-group\" select=\"None\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"quiz-paper\">\r\n");
      out.write("                    <div id=\"quizes-holder\">\r\n");
      out.write("                        <div id=\"quiz\" index=\"None\">\r\n");
      out.write("                            <ol start=\"1\">\r\n");
      out.write("                                <li id=\"quiz-question\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem minima voluptate et unde error adipisci atque sunt, ad sapiente, dolore itaque laboriosam nobis? Pariatur temporibus sapiente ex architecto error perferendis.</li>\r\n");
      out.write("                                <ul id=\"quiz-answers\" given=\"None\" count=\"4\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label class=\"quiz-answer\" id=\"1\" onclick=\"setAnswerAs(1)\">Lorem ipsum dolor sit amet\r\n");
      out.write("                                            <input type=\"radio\" name=\"radio\">\r\n");
      out.write("                                            <span class=\"checkmark\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label class=\"quiz-answer\" id=\"2\" onclick=\"setAnswerAs(2)\">Lorem ipsum dolor sit amet\r\n");
      out.write("                                            <input type=\"radio\" name=\"radio\">\r\n");
      out.write("                                            <span class=\"checkmark\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label class=\"quiz-answer\" id=\"3\" onclick=\"setAnswerAs(3)\">Lorem ipsum dolor sit amet\r\n");
      out.write("                                            <input type=\"radio\" name=\"radio\">\r\n");
      out.write("                                            <span class=\"checkmark\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label class=\"quiz-answer\" id=\"4\" onclick=\"setAnswerAs(4)\">Lorem ipsum dolor sit amet\r\n");
      out.write("                                            <input type=\"radio\" name=\"radio\">\r\n");
      out.write("                                            <span class=\"checkmark\"></span>\r\n");
      out.write("                                        </label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"submit-area\">\r\n");
      out.write("                            <button class=\"button\" id=\"answer-submit\" onclick=\"goNext()\">Next</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"quizes-options\">\r\n");
      out.write("                        <span id=\"headder\"><svg xmlns=\"http://www.w3.org/2000/svg\" height=\"20\" width=\"20\"><path d=\"M10.021 18.021Q9.167 18.021 8.573 17.417Q7.979 16.812 7.979 15.979Q7.979 15.125 8.573 14.51Q9.167 13.896 10.021 13.896Q10.875 13.896 11.469 14.5Q12.062 15.104 12.062 15.958Q12.062 16.812 11.469 17.417Q10.875 18.021 10.021 18.021ZM10.021 12.042Q9.167 12.042 8.573 11.448Q7.979 10.854 7.979 10Q7.979 9.146 8.573 8.552Q9.167 7.958 10.021 7.958Q10.875 7.958 11.469 8.552Q12.062 9.146 12.062 10Q12.062 10.854 11.469 11.448Q10.875 12.042 10.021 12.042ZM10.021 6.104Q9.167 6.104 8.573 5.49Q7.979 4.875 7.979 4.021Q7.979 3.167 8.573 2.573Q9.167 1.979 10.021 1.979Q10.875 1.979 11.469 2.573Q12.062 3.167 12.062 4.021Q12.062 4.875 11.469 5.49Q10.875 6.104 10.021 6.104Z\"/></svg>Quiz navigation</span>\r\n");
      out.write("                        <span id=\"container\">\r\n");
      out.write("                            <fieldset>\r\n");
      out.write("                                <legend>All Questions</legend>\r\n");
      out.write("                                <button class=\"button question-box active\" onclick=\"getQuestion(this.innerText)\">1</button>\r\n");
      out.write("                                <button class=\"button question-box\" onclick=\"getQuestion(this.innerText)\">2</button>\r\n");
      out.write("                                <button class=\"button question-box\" onclick=\"getQuestion(this.innerText)\">3</button>\r\n");
      out.write("                                <button class=\"button question-box\" onclick=\"getQuestion(this.innerText)\">4</button>\r\n");
      out.write("                                <button class=\"button question-box\" onclick=\"getQuestion(this.innerText)\">5</button>\r\n");
      out.write("                            </fieldset>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
