/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-10 07:07:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("            <title>Profile</title>\r\n");
      out.write("            <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/headfoot.css\">\r\n");
      out.write("            <link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/home.css\">\r\n");
      out.write("            <script type=\"text/javascript\" src=\"js/index.js\"></script>\r\n");
      out.write("    <!--Bootstrap website link to get social media icons(use.fontawesome.com)-->\r\n");
      out.write("            <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"https://use.fontawesome.com/releases/v5.13.0/css/all.css\"\r\n");
      out.write("            integrity=\"sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V\"\r\n");
      out.write("            crossorigin=\"anonymous\"/> \r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("    <!--navigation bar-->\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"home.html\"><img src=\"Images/logo.jpeg\" class=\"logo\"></a>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"PHP/home.php\">Home</a></li>\r\n");
      out.write("                <li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"contact.html\">Contact</a></li>\r\n");
      out.write("                <li><a href=\"results.html\">Results</a></li>\r\n");
      out.write("                <li><a href=\"exams.html\">Exams</a></li>\r\n");
      out.write("                <li><a href=\"exams.html\">Profile</a></li>\r\n");
      out.write("               \r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>	\r\n");
      out.write("        <center>\r\n");
      out.write("        <table border=\"2px\" style=\" color:orangered; margin:10px; padding:10px;\">\r\n");
      out.write("            <tr >\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">First Name</th>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">");
      out.print(session.getAttribute("fname") );
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">Last Name:</th>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">");
      out.print(session.getAttribute("lname") );
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">Email:</th>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">");
      out.print( session.getAttribute("email") );
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">Birth Day:</th>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">");
      out.print(session.getAttribute("birthday") );
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th style=\" color:orangered; margin:30px; padding:30px;\">Gender:</th>\r\n");
      out.write("              	<th style=\" color:orangered; margin:30px; padding:30px;\">");
      out.print(session.getAttribute("gender") );
      out.write("</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("        <a href=\"update_profile.jsp\">\r\n");
      out.write("        <input type=\"button\" value=\"update\" name=\"update\" >\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("         <a href=\"delete_profile.jsp\">\r\n");
      out.write("        <input type=\"button\" value=\"Delete My Account\" name=\"delete\" >\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </center>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
